### ISSUE TITLE
semantic release upgrade

### ISSUE THREAD

**Issue by guymi** [TheUnderScorer/nx-semantic-release#112]
Currently, the semantic-release version is 20.0.1 
Is there an issue with upgrading this package to the latest one - 23.0.8?

**Comment by TheUnderScorer** [comment]
Hey @guymi!

The main problem is that the package was migrated to ESM format, so it requires some workarounds to work with NX and semantic-release-plugin-decorators.

I have plans to update the dependencies, it's somewhat in progress [here](https://github.com/TheUnderScorer/nx-semantic-release/pull/104/files), but it will take a while since I also don't have much time to spare on this repo right now.

**Comment by guymi** [comment]
Thank you so much for your help and work on this

**Comment by NickDub** [comment]
Hello, any news about this update ?
