### ISSUE TITLE
Please update @semantic-release/npm version

### ISSUE THREAD

**Issue by tamascsaba** [TheUnderScorer/nx-semantic-release#99]
semver@7.0.0 vulnerable to Regular Expression Denial of Service please update `@semantic-release/npm `
<img width="781" alt="image" src="https://github.com/TheUnderScorer/nx-semantic-release/assets/3479963/46818baf-ac95-4f7a-882d-aa4048b8595e">

**Comment by TheUnderScorer** [comment]
Hey @tamascsaba, pls update the plugin to latest version (I see that you are still on 1.0.2), at some point the npm package was updated to 9.0.2 :)

**Comment by Balvajs** [comment]
> I see that you are still on 1.0.2

It may not be clear from that screenshot, but it suggests to install `1.0.2` because that's a version that doesn't have dependencies with that vulnerability.
<img width="886" alt="image" src="https://github.com/TheUnderScorer/nx-semantic-release/assets/16807011/669a9ce3-165a-4bca-91b8-23f2b3463792">

Here is the [vulnerability link](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw).
